import polars as pl


def get_dtypes():
    return {'hosp/admissions': {'subject_id': pl.Int64,
                                'hadm_id': pl.Int64,
                                'admittime': pl.Datetime,
                                'dischtime': pl.Datetime,
                                'deathtime': pl.Datetime,
                                'admission_type': pl.Utf8,
                                'discharge_location': pl.Utf8,
                                'insurance': pl.Utf8,
                                'language': pl.Utf8,
                                'marital_status': pl.Utf8,
                                'race': pl.Utf8,
                                'edregtime': pl.Datetime,
                                'edouttime': pl.Datetime,
                                'hospital_expire_flag': pl.Int64},

            'hosp/emar': {'subject_id': pl.Int64,
                          'hadm_id': pl.Int64,
                          'emar_id': pl.Utf8,
                          'emar_seq': pl.Int64,
                          'poe_id': pl.Utf8,
                          'pharmacy_id': pl.Int64,
                          'charttime': pl.Datetime,
                          'medication': pl.Utf8,
                          'event_txt': pl.Utf8,
                          'scheduletime': pl.Datetime,
                          'storetime': pl.Datetime},

            'hosp/emar_detail': {'subject_id': pl.Int64,
                                 'emar_id': pl.Utf8,
                                 'emar_seq': pl.Int64,
                                 'parent_field_ordinal': pl.Utf8,
                                 'administration_type': pl.Utf8,
                                 'pharmacy_id': pl.Int64,
                                 'barcode_type': pl.Utf8,
                                 'reason_for_no_barcode': pl.Utf8,
                                 'complete_dose_not_given': pl.Utf8,
                                 'dose_due': pl.Utf8,
                                 'dose_due_unit': pl.Utf8,
                                 'dose_given': pl.Utf8,
                                 'dose_given_unit': pl.Utf8,
                                 'will_remainder_of_dose_be_given': pl.Utf8,
                                 'product_amount_given': pl.Utf8,
                                 'product_unit': pl.Utf8,
                                 'product_code': pl.Utf8,
                                 'product_description': pl.Utf8,
                                 'prior_infusion_rate': pl.Utf8,
                                 'infusion_rate': pl.Utf8,
                                 'infusion_rate_adjustment': pl.Utf8,
                                 'infusion_rate_adjustment_amount': pl.Utf8,
                                 'infusion_rate_unit': pl.Utf8,
                                 'route': pl.Utf8,
                                 'infusion_complete': pl.Utf8,
                                 'completion_interval': pl.Utf8,
                                 'new_iv_bag_hung': pl.Utf8,
                                 'continued_infusion_in_other_location': pl.Utf8,
                                 'restart_interval': pl.Utf8,
                                 'side': pl.Utf8,
                                 'site': pl.Utf8,
                                 'non_formulary_visual_verification': pl.Utf8},

            'hosp/patients': {'subject_id': pl.Int64,
                              'gender': pl.Utf8,
                              'anchor_age': pl.Int64,
                              'anchor_year': pl.Int64,
                              'anchor_year_group': pl.Utf8,
                              'dod': pl.Datetime},

            'hosp/prescriptions': {'subject_id': pl.Int64,
                                   'hadm_id': pl.Int64,
                                   'pharmacy_id': pl.Int64,
                                   'poe_id': pl.Utf8,
                                   'poe_seq': pl.Int64,
                                   'starttime': pl.Datetime,
                                   'stoptime': pl.Datetime,
                                   'drug_type': pl.Utf8,
                                   'drug': pl.Utf8,
                                   'formulary_drug_cd': pl.Utf8,
                                   'gsn': pl.Utf8,
                                   'ndc': pl.Utf8,
                                   'prod_strength': pl.Utf8,
                                   'form_rx': pl.Utf8,
                                   'dose_val_rx': pl.Utf8,
                                   'form_val_disp': pl.Utf8,
                                   'form_unit_disp': pl.Utf8,
                                   'doses_per_24_hrs': pl.Int64,
                                   'route': pl.Utf8},

            'hosp/diagnoses_icd': {'subject_id': pl.Int64,
                                   'hadm_id': pl.Int64,
                                   'seq_num': pl.Int64,
                                   'icd_code': pl.Utf8,
                                   'icd_version': pl.Int64},

            'icu/chartevents': {'subject_id': pl.Int64,
                                'hadm_id': pl.Int64,
                                'stay_id': pl.Int64,
                                'itemid': pl.Int64,
                                'value': pl.Utf8,
                                'valuenum': pl.Float64,
                                'valueuom': pl.Utf8,
                                'warning': pl.Float64,
                                'charttime': pl.Datetime,
                                'storetime': pl.Datetime},

            'icu/d_items': {'itemid': pl.Int64,
                            'label': pl.Utf8,
                            'abbreviation': pl.Utf8,
                            'linksto': pl.Utf8,
                            'category': pl.Utf8,
                            'unitname': pl.Utf8,
                            'param_type': pl.Utf8,
                            'lownormalvalue': pl.Float64,
                            'highnormalvalue': pl.Float64},

            'icu/inputevents': {'subject_id': pl.Int64,
                                'hadm_id': pl.Int64,
                                'stay_id': pl.Int64,
                                'itemid': pl.Int64,
                                'amount': pl.Float64,
                                'amountuom': pl.Utf8,
                                'rate': pl.Float64,
                                'rateuom': pl.Utf8,
                                'orderid': pl.Int64,
                                'linkorderid': pl.Int64,
                                'ordercategoryname': pl.Utf8,
                                'secondaryordercategoryname': pl.Utf8,
                                'ordercomponenttypedescription': pl.Utf8,
                                'ordercategorydescription': pl.Utf8,
                                'patientweight': pl.Float64,
                                'totalamount': pl.Float64,
                                'totalamountuom': pl.Utf8,
                                'isopenbag': pl.Int64,
                                'continueinnextdept': pl.Int64,
                                'statusdescription': pl.Utf8,
                                'originalamount': pl.Float64,
                                'originalrate': pl.Float64,
                                'starttime': pl.Datetime,
                                'endtime': pl.Datetime,
                                'storetime': pl.Datetime}
            }
